default:
  image: docker:26.0.0
  services:
    - name: docker:26.0.0-dind

stages:
- build
# - test
- release
- deploy

variables:
  #MY_GITLAB_REGISTRY: registry.rdlow.ru
  
  #REGISTRY_USERNAME: nva
  #REGISTRY_PASS: 9086620032vN
  CONTAINER_TEST_IMAGE: automation-kernel:test
  CONTAINER_RELEASE_IMAGE: automation-kernel:latest
#registry.rdlow.ru/politeh/

before_script:
   - echo $GITLAB_USER_LOGIN
   - echo $GITLAB_USER_NAME
   - echo $CI_REGISTRY_USER
   - echo $CI_PROJECT_PATH
   - echo $CI_REGISTRY_PASSWORD
   - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASS $CI_REGISTRY
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE $CI_REGISTRY/politeh/automation-kernel/$CONTAINER_TEST_IMAGE
    - docker push $CI_REGISTRY/politeh/automation-kernel/$CONTAINER_TEST_IMAGE
  tags:
    - runner-anoshko-1

# test1:
#   stage: test
#   script:
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests

# test2:
#   stage: test
#   script:
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

# release-image:
#   stage: release
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master