default:
  image: docker:26.0.0
  services:
    - name: docker:26.0.0-dind

stages:
- build
# - test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: registry.rdlow.ru/politeh/automation-kernel:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.rdlow.ru/politeh/automation-kernel:latest

# before_script:
#   - docker login -u nva -p 9086620032vN registry.rdlow.ru

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - runner-anoshko-1

# test1:
#   stage: test
#   script:
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/tests

# test2:
#   stage: test
#   script:
#     - docker run $CONTAINER_TEST_IMAGE /script/to/run/another/test

# release-image:
#   stage: release
#   script:
#     - docker pull $CONTAINER_TEST_IMAGE
#     - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
#     - docker push $CONTAINER_RELEASE_IMAGE
#   only:
#     - master

# deploy:
#   stage: deploy
#   script:
#     - ./deploy.sh
#   only:
#     - master