default:
  image: docker:26.0.0
  services:
    - name: docker:26.0.0-dind

stages:
- build
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: automation-kernel:test
  CONTAINER_RELEASE_IMAGE: automation-kernel:latest


before_script:
   - docker login -u $CI_REGISTRY_USER  -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_RELEASE_IMAGE $CI_REGISTRY/politeh/automation-kernel/$CONTAINER_RELEASE_IMAGE
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CONTAINER_TEST_IMAGE
  tags:
    - runner-anoshko-1


deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker run -d -p 5000:5000 $CONTAINER_RELEASE_IMAGE
  tags:
    - runner-anoshko-1